FROM python:3.10-slim

WORKDIR /app

COPY . .

RUN python3 -m pip install -r requirements.txt

RUN python3 -m flask db init
RUN python3 -m flask db migrate 
RUN python3 -m flask db upgrade


CMD [ "gunicorn", "-b", "0.0.0.0:5000" , "app:app" ]
